### ISSUE TITLE
Update the Readme a little bit please

### ISSUE THREAD

**Issue by WebCrew** [alchemMX/codoforum_mov_theme#1]
Hi @alchemMX 

First of all - **great design** - I like it a lot and you did **a fantastic job**, I like it even more than my themes and I'm a little pissed off that I have to keep using my theme because it serves as a "demo".

I just wanted to **suggest** that you please add information to your **readme** such as users e.g. how to integrate social links or change the footer text or change the header image. Many of the **CF** users have little or no basic understanding of **HTML**, so such guides may be useful.

Kind regards and thx,

Andy 💯

**Comment by alchemMX** [comment]
This is work in progress, after I release the next version it will have a built in wiki.

Kind regards, 
Alchem.

**Comment by WebCrew** [comment]
great idea, but a lot of work :)
